name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install flutter
        uses: tnc1997/github-actions/actions/setup-flutter@setup-flutter_v1
        with:
          channel: dev
      - name: Test
        run: |
          chromedriver --port=4444 &
          sleep 10
          flutter doctor
          flutter upgrade
          flutter packages get
          flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server
  build_android:
    name: Build android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install flutter
        uses: tnc1997/github-actions/actions/setup-flutter@setup-flutter_v1
        with:
          channel: dev
      - name: Build android
        run: |
          flutter packages get
          flutter build apk
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-release.apk
  build_web:
    name: Build web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install flutter
        uses: tnc1997/github-actions/actions/setup-flutter@setup-flutter_v1
        with:
          channel: dev
      - name: Build web
        run: |
          flutter packages get
          flutter build web
      - name: Deploy web
        uses: FirebaseExtended/action-hosting-deploy@v0
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ACE_RESOLVER_317419 }}
          projectId: ace-resolver-317419
          repoToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: build/web
  build_windows:
    name: Build windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install flutter
        uses: tnc1997/github-actions/actions/setup-flutter@setup-flutter_v1
        with:
          channel: dev
      - name: Enable windows
        run: flutter config --enable-windows-desktop
      - name: Build windows
        run: |
          flutter packages get
          flutter build windows
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: build\windows\runner\Release
